site_name: Chinese Checkers
site_url: https://cpp.ruc.megaowier.cc

# Repository
repo_name: 'MegaOwIer/ChineseCheckers'
repo_url: https://github.com/MegaOwIer/ChineseCheckers

# Contents
nav:
  - Home: index.md
  - Instructions:
    - 游戏玩法: instructions/inst-introduction.md
    - 游戏规则: instructions/inst-rule.md
  - Tasks:
    - Task 0: instructions/Task0.md
    - Task 1: instructions/Task1.md
  - Teams:
    - Team 0:
      - 小组简介: submission/Team0/index.md
      - 第一阶段总结: submission/Team0/stage1/report.md
    - Team 1:
      - 小组简介: submission/Team1/index.md
    - Team 2:
      - 小组简介: submission/Team2/1.md 
    - Team 3:
      - 小组简介: submission/Team3/task0.md
    - Team 4:
      - 小组简介: submission/Team4/index.md
    - Team 5:
      - 小组简介: submission/Team5/index.md
    - Team 6:  
      - 小组简介: submission/Team6/index.md
    - Team 7:
      - 小组简介: submission/Team7/index.md
    - Team 8:
      - 小组介绍: submission/Team8/index.md
    - Team 9:
      - 小组简介: submission/Team9/index.md
      - 第一阶段总结: submission/Team9/stage1/report.md
    - Team 10:
      - 小组介绍: submission/Team10/Helloworld.md


# Theme
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'blue'
    accent: 'red'
  include_search_page: false
  search_index_only: true

  feature:
    tabs: true
  font:
    # text: 'Times New Roman'
    code: 'Fira Mono'

extra_javascript:
  - 'https://cdnjs.loli.net/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde